development:
  access_key_id: AKIAI6R3R43KYSW44LCQ
  secret_access_key: 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
  bucket: bozzuto.smartrent.app.s3.stg
test:
  access_key_id: AKIAI6R3R43KYSW44LCQ
  secret_access_key: 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
  bucket: bozzuto.smartrent.app.s3.stg
stage:
  access_key_id: AKIAI6R3R43KYSW44LCQ
  secret_access_key: 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
  bucket: bozzuto.smartrent.app.s3.stg
production:
  access_key_id: AKIAI6R3R43KYSW44LCQ
  secret_access_key: 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
  bucket: bozzuto.smartrent.app.s3