development:
  access_key_id: AKIAICJX5ULNO7BJ3IYA
  secret_access_key: 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
  bucket: crm.bozzuto.com
test:
  access_key_id: AKIAICJX5ULNO7BJ3IYA
  secret_access_key: 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
  bucket: crm.bozzuto.com.test
stage:
  access_key_id: AKIAICJX5ULNO7BJ3IYA
  secret_access_key: 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
  bucket: crm.bozzuto.com.stg
production:
  access_key_id: AKIAICJX5ULNO7BJ3IYA
  secret_access_key: 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
  bucket: crm.bozzuto.com