---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: crm-test
  domain: bozzuto.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web_tools
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_server
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: graphite_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_scheduler
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: resque_worker
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: redis
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mongodb
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-08e4aa18080a9a96d
  image_type: m4.large
  image_id: ami-7e9b7c11
  security_groups:
  - common
  - web
  - web_tools
  zone: eu-central-1b
  network: 
  gateway: 
  external_host: ec2-52-201-27-62.compute-1.amazonaws.com
  external_ip: 52.201.27.62
  internal_host: ip-172-16-1-152.ec2.internal
  internal_ip: 172.16.1.152
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
  vpc: {}
