resque_scheduler_pid_file: /var/run/crm-resque-scheduler.pid
resque_scheduler_log_file: /var/log/crm-resque-scheduler.log

gems: [resque-scheduler]

role_dependencies:
  web_tools: [resque_scheduler]
